### ISSUE TITLE
call to undefined function wp_get_current_user()

### ISSUE THREAD

**Issue by ChrisButterworth** [jawngee/ILab-Media-Tools#6]
Just tried to install and set up plugin but once activated getting this message

`Fatal error: Uncaught Error: Call to undefined function ILAB\MediaCloud\Utilities\wp_get_current_user() in /Users/chrisbutterworth/Sites/brandidentity/wp/web/app/plugins/ilab-media-tools/classes/Utilities/Prefixer.php:124 Stack trace: #0 /Users/chrisbutterworth/Sites/brandidentity/wp/web/app/plugins/ilab-media-tools/classes/Utilities/Prefixer.php(163): ILAB\MediaCloud\Utilities\Prefixer->parsePrefix('uploads/@{date:...', NULL) #1 /Users/chrisbutterworth/Sites/brandidentity/wp/web/app/plugins/ilab-media-tools/classes/Cloud/Storage/StorageSettings.php(122): ILAB\MediaCloud\Utilities\Prefixer::Parse('uploads/@{date:...', NULL) #2 /Users/chrisbutterworth/Sites/brandidentity/wp/web/app/plugins/ilab-media-tools/classes/Tools/Storage/StorageTool.php(371): ILAB\MediaCloud\Cloud\Storage\StorageSettings::prefix(NULL) #3 /Users/chrisbutterworth/Sites/brandidentity/wp/web/wp/wp-includes/class-wp-hook.php(298): ILAB\MediaCloud\Tools\Storage\StorageTool->getUploadDir(Array) #4 /Users/chrisbutterworth/Sites/brandidentity/wp/web/wp/wp-in in /Users/chrisbutterworth/Sites/brandidentity/wp/web/app/plugins/ilab-media-tools/classes/Utilities/Prefixer.php on line 124`

Any ideas?

**Comment by ChrisButterworth** [comment]
More info:
Using DigitalOcean Spaces
Trying to use a custom prefix – removing this makes it work

**Comment by jawngee** [comment]
What custom prefix?  
Also, what other plugins are you using?

The error is caused because somehow the `parsePrefix()` function is being called before WordPress is fully loaded.

**Comment by ChrisButterworth** [comment]
I was trying to use `uploads/@{date:Y/m}`
I have WooCommerce, WordPress SEO by Yoast and Advanced Custom Fields.

**Comment by necevil** [comment]
Same issue here on a new install.  Also have Yoast (no woo or advanced custom fields).
Actually crashed the whole site, going to try to modify the settings via the database as opposed to roll back.  

Will post back when I figure out what the db schema for the plugin looks like incase anyone else has the issue.

For reference I also used: `@{date:Y/m}`
